version: "3"
services:
  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
  openresty:
    image: openresty/openresty:alpine
    environment:
     - LUA_PATH=/usr/local/openresty/nginx/lua/?.lua
    ports:
     - "9090:9090"
    volumes:
     - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro"
     - "./lua:/usr/local/openresty/nginx/lua:ro"

